language: node_js
sudo: required
node_js:
  - "0.12"
services:
  - docker
addons:
  - postgresql: "9.4"
env:
  - ELASTIC_BEANSTALK_LABEL=$TRAVIS_TAG
before_script:
  - make migrate
after_success:
  - make coverage
before_deploy:
  - make build
  - docker login -e $DOCKER_EMAIL -p $DOCKER_PASSWORD -u $DOCKER_USERNAME
  - make docker-push
deploy:
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^v[0-9].[0-9].[0-9]$"
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-east-1
  app: liddellj-app
  env: liddellj-staging
  zip-file: Dockerrun.aws.json
  skip_cleanup: true
  bucket_name: liddellj
  bucket_path: eb-deployments