language: node_js
node_js:
  - "0.12"
before_deploy:
  - mkdir build
  - npm run build
  - zip -r build/app.zip . -x@exclude.lst
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-east-1
  app: liddellj-app
  env: liddellj-env
  zip-file: build/app.zip
  skip_cleanup: true
  bucket_name: liddellj
  bucket_path: eb-deployments