language: node_js
sudo: required
node_js:
  - "0.12"
services:
  - docker
env:
  - ELASTIC_BEANSTALK_LABEL=$TRAVIS_TAG
after_success:
  - npm run build
  - npm run coverage
  - docker login -e $DOCKER_EMAIL -p $DOCKER_PASSWORD -u $DOCKER_USERNAME
  - npm run docker-build
  - npm run docker-push
before_deploy:
  - npm run docker-aws-version
deploy:
  on:
    tags: true
    all_branches: true
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-east-1
  app: liddellj-app
  env: liddellj-env
  zip-file: Dockerrun.aws.json
  skip_cleanup: true
  bucket_name: liddellj
  bucket_path: eb-deployments