language: node_js
sudo: required
node_js:
  - "0.12"
services:
  - docker
env:
  - ELASTIC_BEANSTALK_LABEL=$TRAVIS_TAG
before_script:
  - wget http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.tar.gz
  - tar xfz dynamodb_local_latest.tar.gz
  - java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -inMemory &
after_success:
  - npm run coverage
before_deploy:
  - npm run docker-build
  - docker login -e $DOCKER_EMAIL -p $DOCKER_PASSWORD -u $DOCKER_USERNAME
  - npm run docker-push
  - npm run docker-aws-version
deploy:
  on:
    tags: true
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-east-1
  app: liddellj-app
  env: liddellj-env
  zip-file: Dockerrun.aws.json
  skip_cleanup: true
  bucket_name: liddellj
  bucket_path: eb-deployments